workflows:
  ios-app:
    name: iOS Build (No Code Signing)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
      - |
        cd ios
        xcode-project build-ipa \
          --workspace Runner.xcworkspace \
          --scheme Runner \
          --export-options-plist export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
