workflows:
  ios-app:
    name: iOS Build (No Code Signing)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
      - xcode-project build-ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
