workflows:
  ios-app:
    name: iOS Build (No Code Signing)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
      - |
        cd ios
        xcodebuild archive \
          -workspace Runner.xcworkspace \
          -scheme Runner \
          -archivePath build/Runner.xcarchive \
          CODE_SIGNING_ALLOWED=NO
        xcodebuild -exportArchive \
          -archivePath build/Runner.xcarchive \
          -exportOptionsPlist export_options.plist \
          -exportPath build/ios/ipa \
          CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
